// Run after changing brand-tokens.cjs: `node scripts/brand/generate.cjs [path/to/30grow-brand-kit]`.
// Writes app/brand-tokens.css. With the kit folder (unzipped), also refreshes logos/favicons/PWA icons from the official files.
const fs = require('node:fs');
const path = require('node:path');
const {GROW, GREEN} = require('../../lib/brand-tokens.cjs');
const root = path.resolve(__dirname, '../..');
const write = (name, content) => fs.writeFileSync(path.join(root, name), content);
const rgb = hex => hex.slice(1).match(/../g).map(x => parseInt(x,16)).join(' ');
const cssName = name => name.replace(/[A-Z]/g, x => '-' + x.toLowerCase());
const light = {canvas:GROW.background,'canvas-alt':'#F1F5F9',surface:GROW.surface,ink:GROW.navy,'ink-secondary':GROW.textSecondary,'ink-faint':GROW.textSecondary,'ink-label':GROW.textSecondary,border:GROW.border,'input-border':GROW.inputBorder,action:GROW.action,'action-hover':GROW.actionHover,'on-action':GROW.onAction,teal:GROW.teal,navy:GROW.navy,success:'#15803D',danger:'#DC2626',warning:'#B45309',info:'#0369A1',soft:GROW.textSecondary};
for(const [key,val] of Object.entries(GREEN)) light['brand-'+key]=val;
write('app/brand-tokens.css', '/* Generated by scripts/brand/generate.cjs. Edit lib/brand-tokens.cjs. */\n:root {\n'+Object.entries(GROW).map(([key,val])=>`  --grow-${cssName(key)}: ${val};`).join('\n')+'\n'+Object.entries(light).map(([key,val])=>`  --${key}: ${rgb(val)};`).join('\n')+'\n  --brand-logo-ink: var(--grow-navy);\n  --color-focus-ring: var(--grow-action);\n}\n');

const kit = process.argv[2];
if (!kit) process.exit(0);
const copies = {
  'logo/30grow-logo.svg': 'public/brand/logo-wordmark.svg',
  'logo/30grow-logo-dark.svg': 'public/brand/logo-wordmark-dark.svg',
  'logo/30grow-logo-white.svg': 'public/brand/logo-wordmark-white.svg',
  'symbol/30grow-symbol.svg': 'public/brand/logo-symbol.svg',
  'symbol/30grow-symbol-dark.svg': 'public/brand/logo-symbol-dark.svg',
  'favicon/favicon.svg': 'public/brand/favicon.svg',
  'favicon/favicon-16x16.png': 'public/brand/logo-16.png',
  'favicon/favicon-32x32.png': 'public/brand/logo-32.png',
  'favicon/favicon-48x48.png': 'public/brand/logo-48.png',
  'favicon/favicon-64x64.png': 'public/brand/logo-64.png',
  'pwa/icon-192x192.png': 'public/brand/logo-192.png',
  'pwa/icon-512x512.png': 'public/brand/logo-512.png',
  'pwa/icon-maskable-192x192.png': 'public/brand/logo-maskable-192.png',
  'pwa/icon-maskable-512x512.png': 'public/brand/logo-maskable-512.png',
  'app/app-icon-1024.png': 'public/brand/logo-mark.png',
  'app/ios/apple-touch-icon.png': 'app/apple-icon.png',
  'favicon/favicon.ico': ['app/favicon.ico', 'public/favicon.ico'],
};
for (const [from, to] of Object.entries(copies)) {
  for (const dest of [].concat(to)) fs.copyFileSync(path.join(kit, from), path.join(root, dest));
}
(async () => {
  const sharp = require('sharp');
  const master = path.join(kit, 'app/app-icon-1024.png');
  for (const size of [128, 256]) await sharp(master).resize(size, size).png().toFile(path.join(root, `public/brand/logo-${size}.png`));
  fs.copyFileSync(path.join(kit, 'pwa/icon-512x512.png'), path.join(root, 'app/icon.png'));
})();
