/** English titles/descriptions for type-pair compatibility (dashboard). Levels match COMPAT_RAW. */
export const COMPAT_EN = {
  '1-2': { level: 'synergy', title: 'Quality + Care', desc: 'The Perfectionist (T1) raises standards; the Helper (T2) humanizes the process. Together they tend to deliver excellence with empathy.' },
  '1-3': { level: 'neutral', title: 'Standard vs Result', desc: 'Both performance-focused, but the Perfectionist (T1) prioritizes the right process while the Achiever (T3) prioritizes outcomes. Friction over how vs how much.' },
  '1-4': { level: 'tension', title: 'Critique vs Sensitivity', desc: 'The Perfectionist (T1) critiques to improve; the Individualist (T4) may hear critique as personal rejection. Needs careful communication and clear feedback norms.' },
  '1-5': { level: 'synergy', title: 'Rigor + Analysis', desc: 'Perfectionist (T1) and Investigator (T5) both value precision, competence, and quality. Strong on projects needing depth and accuracy.' },
  '1-6': { level: 'synergy', title: 'Integrity + Loyalty', desc: 'Perfectionist (T1) and Loyalist (T6) share responsibility and commitment. Build mutual trust easily.' },
  '1-7': { level: 'tension', title: 'Rules vs Freedom', desc: 'The Perfectionist (T1) follows norms strictly; the Enthusiast (T7) bends them creatively. Frequent friction without alignment.' },
  '1-8': { level: 'tension', title: 'Control vs Control', desc: 'Perfectionist (T1) and Challenger (T8) both believe they know how things should be done—and disagree. Power struggles are common without mutual respect.' },
  '1-9': { level: 'synergy', title: 'Action + Harmony', desc: 'The Perfectionist (T1) executes; the Peacemaker (T9) smooths the climate. Good pair to lead teams—one sets the standard, the other keeps the mood.' },
  '2-3': { level: 'neutral', title: 'Care vs Performance', desc: 'The Helper (T2) focuses on people; the Achiever (T3) on results. Complementary but may see each other as opposites.' },
  '2-4': { level: 'synergy', title: 'Care + Depth', desc: 'Helper (T2) and Individualist (T4) value genuine emotional connection. Build deep, trusting work relationships.' },
  '2-5': { level: 'tension', title: 'Closeness vs Distance', desc: 'The Helper (T2) wants constant connection; the Investigator (T5) needs space and privacy. T2 may feel rejected where there is only autonomy.' },
  '2-6': { level: 'synergy', title: 'Care + Loyalty', desc: 'Helper (T2) and Loyalist (T6) are a highly reliable pair. Both put the other first and build lasting bonds.' },
  '2-7': { level: 'neutral', title: 'Warmth vs Enthusiasm', desc: 'Both people-oriented and positive. The Enthusiast (T7) may seem shallow to the Helper (T2); T2 too intense to T7.' },
  '2-8': { level: 'tension', title: 'Care vs Confrontation', desc: 'The Helper (T2) tends to seek a smooth connection; the Challenger (T8) is direct and assertive. They may see each other as manipulative vs insensitive.' },
  '2-9': { level: 'synergy', title: 'Generosity + Harmony', desc: 'Helper (T2) and Peacemaker (T9) are naturally gentle and cooperative. Pleasant environments, but may avoid necessary conflict.' },
  '3-4': { level: 'tension', title: 'Image vs Authenticity', desc: 'The Achiever (T3) adapts image to context; the Individualist (T4) values authenticity above all. Opposite views of “truth”.' },
  '3-5': { level: 'neutral', title: 'Results vs Depth', desc: 'The Achiever (T3) wants fast results; the Investigator (T5) wants full analysis. Pace tension but complementary in delivery.' },
  '3-6': { level: 'tension', title: 'Trust vs Doubt', desc: 'The Achiever (T3) projects confidence; the Loyalist (T6) questions motives. T6 may distrust T3’s polished image.' },
  '3-7': { level: 'synergy', title: 'Results + Energy', desc: 'Achiever (T3) and Enthusiast (T7) are a high-performance pair. Optimistic, fast, achievement-oriented. Risk of skimming depth.' },
  '3-8': { level: 'neutral', title: 'Ambition + Power', desc: 'Achiever (T3) and Challenger (T8) are both assertive and outcome-driven. Powerful allies or intense rivals.' },
  '3-9': { level: 'tension', title: 'Ambition vs Inertia', desc: 'The Achiever (T3) wants to speed up; the Peacemaker (T9) prefers a natural pace. Mutual frustration over rhythm and urgency.' },
  '4-5': { level: 'synergy', title: 'Creativity + Depth', desc: 'Individualist (T4) and Investigator (T5) both live in deep layers—one emotional, one intellectual. High originality.' },
  '4-6': { level: 'neutral', title: 'Intensity vs Caution', desc: 'The Individualist (T4) dives into feelings; the Loyalist (T6) prefers safety. Can support each other with patience.' },
  '4-7': { level: 'tension', title: 'Depth vs Lightness', desc: 'The Individualist (T4) wants to go deep emotionally; the Enthusiast (T7) tends to avoid heaviness. T7 seems shallow to T4; T4 heavy to T7.' },
  '4-8': { level: 'neutral', title: 'Vulnerability vs Force', desc: 'Individualist (T4) and Challenger (T8) are both intense and authentic. Deep bond if T8 softens and T4 steadies.' },
  '4-9': { level: 'synergy', title: 'Beauty + Peace', desc: 'Individualist (T4) and Peacemaker (T9) value depth and meaningful experience. Create space for creativity and reflection.' },
  '5-6': { level: 'synergy', title: 'Analysis + Caution', desc: 'Investigator (T5) and Loyalist (T6) both think before acting and anticipate risk. Excellent for planning and risk management.' },
  '5-7': { level: 'tension', title: 'Containment vs Expansion', desc: 'The Investigator (T5) conserves resources; the Enthusiast (T7) expands them. T7 may drain T5; T5 frustrates T7 with limits.' },
  '5-8': { level: 'neutral', title: 'Mind vs Force', desc: 'The Investigator (T5) leads with knowledge; the Challenger (T8) with assertiveness. Mutual respect or clashing styles.' },
  '5-9': { level: 'synergy', title: 'Quiet + Reflection', desc: 'Investigator (T5) and Peacemaker (T9) prefer calm settings and autonomous work. Naturally respect each other’s space.' },
  '6-7': { level: 'neutral', title: 'Security vs Adventure', desc: 'The Loyalist (T6) wants predictability; the Enthusiast (T7) wants novelty. Balance risk together if trust exists.' },
  '6-8': { level: 'tension', title: 'Authority vs Questioning', desc: 'The Challenger (T8) acts with authority; the Loyalist (T6) questions motives and fears control. Needs high transparency.' },
  '6-9': { level: 'synergy', title: 'Loyalty + Harmony', desc: 'Loyalist (T6) and Peacemaker (T9) are a very stable, reliable pair. Both prioritize the group and avoid unnecessary conflict.' },
  '7-8': { level: 'neutral', title: 'Energy + Power', desc: 'Enthusiast (T7) and Challenger (T8) are both expansive and strong-presence. Dynamic force or clash over who dominates space.' },
  '7-9': { level: 'synergy', title: 'Lightness + Calm', desc: 'Enthusiast (T7) and Peacemaker (T9) avoid tension and seek positive experiences. May postpone necessary conflict.' },
  '8-9': { level: 'neutral', title: 'Force vs Passivity', desc: 'The Challenger (T8) is direct and confrontational; the Peacemaker (T9) avoids conflict. T9 may give in too much; T8 may dominate unaware.' },
};
