/** English titles/descriptions for type-pair compatibility (dashboard). Levels match COMPAT_RAW. */
export const COMPAT_EN = {
  '1-2': { level: 'synergy', title: 'Quality + Care', desc: 'Type 1 raises standards; type 2 humanizes the process. Together they deliver excellence with empathy.' },
  '1-3': { level: 'neutral', title: 'Standard vs Result', desc: 'Both performance-focused, but 1 prioritizes the right process while 3 prioritizes outcomes. Friction over how vs how much.' },
  '1-4': { level: 'tension', title: 'Critique vs Sensitivity', desc: '1 critiques to improve; 4 hears critique as personal rejection. Needs careful communication and clear feedback norms.' },
  '1-5': { level: 'synergy', title: 'Rigor + Analysis', desc: 'Both value precision, competence, and quality. Strong on projects needing depth and accuracy.' },
  '1-6': { level: 'synergy', title: 'Integrity + Loyalty', desc: 'Shared responsibility and commitment. Build mutual trust easily.' },
  '1-7': { level: 'tension', title: 'Rules vs Freedom', desc: '1 follows norms strictly; 7 bends them creatively. Frequent friction without alignment.' },
  '1-8': { level: 'tension', title: 'Control vs Control', desc: 'Both believe they know how things should be done—and disagree. Power struggles are common without mutual respect.' },
  '1-9': { level: 'synergy', title: 'Action + Harmony', desc: '1 executes; 9 smooths the climate. Good pair to lead teams—one sets the standard, the other keeps the mood.' },
  '2-3': { level: 'neutral', title: 'Care vs Performance', desc: '2 focuses on people; 3 on results. Complementary but may see each other as opposites.' },
  '2-4': { level: 'synergy', title: 'Care + Depth', desc: 'Both value genuine emotional connection. Build deep, trusting work relationships.' },
  '2-5': { level: 'tension', title: 'Closeness vs Distance', desc: '2 wants constant connection; 5 needs space and privacy. 2 may feel rejected where there is only autonomy.' },
  '2-6': { level: 'synergy', title: 'Care + Loyalty', desc: 'Highly reliable pair. Both put the other first and build lasting bonds.' },
  '2-7': { level: 'neutral', title: 'Warmth vs Enthusiasm', desc: 'Both people-oriented and positive. 7 may seem shallow to 2; 2 too intense to 7.' },
  '2-8': { level: 'tension', title: 'Care vs Confrontation', desc: '2 wants smooth connection; 8 is direct and assertive. May see each other as manipulative vs insensitive.' },
  '2-9': { level: 'synergy', title: 'Generosity + Harmony', desc: 'Naturally gentle and cooperative. Pleasant environments, but may avoid necessary conflict.' },
  '3-4': { level: 'tension', title: 'Image vs Authenticity', desc: '3 adapts image to context; 4 values authenticity above all. Opposite views of “truth”.' },
  '3-5': { level: 'neutral', title: 'Results vs Depth', desc: '3 wants fast results; 5 wants full analysis. Pace tension but complementary in delivery.' },
  '3-6': { level: 'tension', title: 'Trust vs Doubt', desc: '3 projects confidence; 6 questions motives. 6 may distrust 3’s polished image.' },
  '3-7': { level: 'synergy', title: 'Results + Energy', desc: 'High-performance pair. Optimistic, fast, achievement-oriented. Risk of skimming depth.' },
  '3-8': { level: 'neutral', title: 'Ambition + Power', desc: 'Both assertive and outcome-driven. Powerful allies or intense rivals.' },
  '3-9': { level: 'tension', title: 'Ambition vs Inertia', desc: '3 wants to speed up; 9 prefers natural pace. Mutual frustration over rhythm and urgency.' },
  '4-5': { level: 'synergy', title: 'Creativity + Depth', desc: 'Both live in deep layers—one emotional, one intellectual. High originality.' },
  '4-6': { level: 'neutral', title: 'Intensity vs Caution', desc: '4 dives into feelings; 6 prefers safety. Can support each other with patience.' },
  '4-7': { level: 'tension', title: 'Depth vs Lightness', desc: '4 wants to go deep emotionally; 7 avoids heaviness. 7 seems shallow to 4; 4 heavy to 7.' },
  '4-8': { level: 'neutral', title: 'Vulnerability vs Force', desc: 'Both intense and authentic. Deep bond if 8 softens and 4 steadies.' },
  '4-9': { level: 'synergy', title: 'Beauty + Peace', desc: 'Both value depth and meaningful experience. Create space for creativity and reflection.' },
  '5-6': { level: 'synergy', title: 'Analysis + Caution', desc: 'Both think before acting and anticipate risk. Excellent for planning and risk management.' },
  '5-7': { level: 'tension', title: 'Containment vs Expansion', desc: '5 conserves resources; 7 expands them. 7 drains 5; 5 frustrates 7 with limits.' },
  '5-8': { level: 'neutral', title: 'Mind vs Force', desc: '5 leads with knowledge; 8 with assertiveness. Mutual respect or clashing styles.' },
  '5-9': { level: 'synergy', title: 'Quiet + Reflection', desc: 'Both prefer calm settings and autonomous work. Naturally respect each other’s space.' },
  '6-7': { level: 'neutral', title: 'Security vs Adventure', desc: '6 wants predictability; 7 wants novelty. Balance risk together if trust exists.' },
  '6-8': { level: 'tension', title: 'Authority vs Questioning', desc: '8 acts with authority; 6 questions motives and fears control. Needs high transparency.' },
  '6-9': { level: 'synergy', title: 'Loyalty + Harmony', desc: 'Very stable, reliable pair. Both prioritize the group and avoid unnecessary conflict.' },
  '7-8': { level: 'neutral', title: 'Energy + Power', desc: 'Both expansive and strong-presence. Dynamic force or clash over who dominates space.' },
  '7-9': { level: 'synergy', title: 'Lightness + Calm', desc: 'Both avoid tension and seek positive experiences. May postpone necessary conflict.' },
  '8-9': { level: 'neutral', title: 'Force vs Passivity', desc: '8 is direct and confrontational; 9 avoids conflict. 9 may give in too much; 8 may dominate unaware.' },
};
