export const TYPE_DATA = {
  1: { name:"O Perfeccionista", short:"Perfeccionista", emoji:"⚖️", color:"#E8C547",
    desc:"Ético, organizado e movido por um profundo senso de certo e errado. Sua voz interior crítica é também o motor de sua excelência.",
    strengths:["Ético","Organizado","Íntegro","Confiável","Detalhista"],
    challenge:"Aceitar a imperfeição como parte do processo.",
    team:"Garante qualidade e padrões elevados. Ideal para revisão, compliance e processos." },
  2: { name:"O Auxiliador", short:"Auxiliador", emoji:"🤝", color:"#E87B47",
    desc:"Caloroso, generoso e intuitivo. Antecipa o que os outros precisam antes mesmo de pedirem.",
    strengths:["Empático","Generoso","Caloroso","Conectado","Atencioso"],
    challenge:"Lembrar que suas próprias necessidades também importam.",
    team:"Cola a equipe. Excelente em atendimento, RH e funções que exigem relação humana." },
  3: { name:"O Realizador", short:"Realizador", emoji:"🏆", color:"#E8A447",
    desc:"Ambicioso, eficiente e carismático. Transforma metas em resultados com impressionante capacidade de adaptação.",
    strengths:["Ambicioso","Eficiente","Carismático","Adaptável","Focado"],
    challenge:"Descobrir quem é além das conquistas.",
    team:"Motor de resultados. Perfeito para vendas, liderança e projetos com prazos claros." },
  4: { name:"O Individualista", short:"Individualista", emoji:"🎭", color:"#9B47E8",
    desc:"Criativo, autêntico e emocionalmente profundo. Busca ser completamente visto e compreendido.",
    strengths:["Criativo","Autêntico","Profundo","Expressivo","Empático"],
    challenge:"Encontrar valor no ordinário e no presente.",
    team:"Traz inovação estética e profundidade. Brilha em design, criação e estratégia criativa." },
  5: { name:"O Investigador", short:"Investigador", emoji:"🔬", color:"#47A8E8",
    desc:"Analítico, independente e perspicaz. Observa antes de agir e acumula conhecimento como recurso.",
    strengths:["Analítico","Independente","Perspicaz","Inovador","Concentrado"],
    challenge:"Sair da mente e engajar mais com o mundo.",
    team:"Especialista nato. Ideal para pesquisa, dados, arquitetura de sistemas e análises complexas." },
  6: { name:"O Leal", short:"Leal", emoji:"🛡️", color:"#47C4E8",
    desc:"Comprometido, responsável e perspicaz sobre riscos. Antecipa problemas, questiona e prepara.",
    strengths:["Leal","Responsável","Precavido","Comprometido","Protetor"],
    challenge:"Confiar em si mesmo tanto quanto confia nos outros.",
    team:"Pilar de confiabilidade. Excelente em segurança, planejamento e funções de longo prazo." },
  7: { name:"O Entusiasta", short:"Entusiasta", emoji:"✨", color:"#47E87B",
    desc:"Espontâneo, otimista e versátil. Vive em modo de expansão permanente e contagia com energia.",
    strengths:["Entusiástico","Criativo","Otimista","Espontâneo","Versátil"],
    challenge:"Encontrar liberdade na profundidade, não na fuga.",
    team:"Gerador de energia e ideias. Ótimo em brainstorming, produto e ambientes ágeis." },
  8: { name:"O Desafiador", short:"Desafiador", emoji:"🔥", color:"#E84747",
    desc:"Assertivo, protetor e direto. Por trás da dureza há um coração que protege intensamente quem ama.",
    strengths:["Assertivo","Protetor","Direto","Corajoso","Decisivo"],
    challenge:"Deixar a vulnerabilidade ser sua maior força.",
    team:"Liderança natural em crise. Perfeito para decisões difíceis e ambientes competitivos." },
  9: { name:"O Pacificador", short:"Pacificador", emoji:"☮️", color:"#47E8C4",
    desc:"Receptivo, paciente e reconfortante. Enxerga todos os lados e cria harmonia onde há conflito.",
    strengths:["Mediador","Paciente","Receptivo","Estável","Harmonizador"],
    challenge:"Priorizar suas necessidades sem culpa.",
    team:"Mediador nato. Essencial em gestão de conflitos, suporte e liderança colaborativa." },
};

const COMPAT_RAW = {
  "1-2":{ level:"synergy",  title:"Qualidade + Cuidado",        desc:"O 1 eleva os padrões; o 2 humaniza o processo. Juntos entregam excelência com empatia." },
  "1-3":{ level:"neutral",  title:"Padrão vs Resultado",         desc:"Ambos focados em performance, mas o 1 prioriza o processo correto enquanto o 3 prioriza o resultado. Podem criar atritos sobre 'como' versus 'quanto'." },
  "1-4":{ level:"tension",  title:"Crítica vs Sensibilidade",    desc:"O 1 critica para melhorar; o 4 interpreta crítica como rejeição pessoal. Requer comunicação cuidadosa e acordos claros de feedback." },
  "1-5":{ level:"synergy",  title:"Rigor + Análise",             desc:"Ambos prezam precisão, competência e qualidade. Trabalham bem em projetos que exigem profundidade e exatidão." },
  "1-6":{ level:"synergy",  title:"Integridade + Lealdade",      desc:"Compartilham valores de responsabilidade e compromisso. Constroem confiança mútua com facilidade." },
  "1-7":{ level:"tension",  title:"Regras vs Liberdade",         desc:"O 1 segue normas com rigor; o 7 as contorna com criatividade. Gera atritos frequentes sem alinhamento." },
  "1-8":{ level:"tension",  title:"Controle vs Controle",        desc:"Dois tipos que sabem como as coisas devem ser feitas — e discordam. Lutas de poder são comuns sem respeito mútuo." },
  "1-9":{ level:"synergy",  title:"Ação + Harmonia",             desc:"O 1 executa; o 9 suaviza. Boa dupla para liderar equipes — um define o padrão, o outro mantém o clima." },
  "2-3":{ level:"neutral",  title:"Cuidado vs Performance",      desc:"O 2 foca nas pessoas; o 3 foca nos resultados. Complementares, mas podem se perceber como opostos." },
  "2-4":{ level:"synergy",  title:"Cuidado + Profundidade",      desc:"Ambos valorizam conexão emocional genuína. Criam relações profundas e de confiança no trabalho." },
  "2-5":{ level:"tension",  title:"Proximidade vs Distância",    desc:"O 2 busca conexão constante; o 5 precisa de espaço e privacidade. O 2 pode sentir rejeição onde há apenas autonomia." },
  "2-6":{ level:"synergy",  title:"Cuidado + Lealdade",          desc:"Dupla extremamente confiável. Ambos colocam o outro em primeiro lugar e constroem vínculos duradouros." },
  "2-7":{ level:"neutral",  title:"Calor vs Entusiasmo",         desc:"Ambos são orientados a pessoas e positivos. O 7 pode parecer superficial ao 2 e o 2 muito intenso ao 7." },
  "2-8":{ level:"tension",  title:"Cuidar vs Confrontar",        desc:"O 2 quer conexão suave; o 8 é direto e assertivo. Podem se perceber como manipulador e insensível mutuamente." },
  "2-9":{ level:"synergy",  title:"Generosidade + Harmonia",     desc:"Dupla naturalmente gentil e cooperativa. Criam ambientes agradáveis, mas podem evitar conflitos necessários." },
  "3-4":{ level:"tension",  title:"Imagem vs Autenticidade",     desc:"O 3 adapta a imagem ao contexto; o 4 valoriza autenticidade acima de tudo. Percepções opostas de 'verdade'." },
  "3-5":{ level:"neutral",  title:"Resultado vs Profundidade",   desc:"O 3 quer resultados rápidos; o 5 quer análise completa. Tensão de ritmo, mas complementares em entrega." },
  "3-6":{ level:"tension",  title:"Confiança vs Desconfiança",   desc:"O 3 projeta confiança; o 6 questiona as motivações. O 6 pode desconfiar da imagem polida do 3." },
  "3-7":{ level:"synergy",  title:"Resultado + Energia",         desc:"Dupla de alta performance. Otimistas, rápidos e orientados a conquistas. Risco de falta de profundidade." },
  "3-8":{ level:"neutral",  title:"Ambição + Poder",             desc:"Ambos assertivos e orientados a resultados. Podem ser aliados poderosos ou rivais intensos." },
  "3-9":{ level:"tension",  title:"Ambição vs Inércia",          desc:"O 3 quer acelerar; o 9 prefere o ritmo natural. Frustração mútua de ritmo e urgência." },
  "4-5":{ level:"synergy",  title:"Criatividade + Profundidade", desc:"Ambos vivem em camadas profundas — um no emocional, outro no intelectual. Grande originalidade." },
  "4-6":{ level:"neutral",  title:"Intensidade vs Precaução",    desc:"O 4 mergulha nas emoções; o 6 prefere segurança. Podem se apoiar com paciência mútua." },
  "4-7":{ level:"tension",  title:"Profundidade vs Leveza",      desc:"O 4 quer mergulhar nas emoções; o 7 foge delas. O 7 parece raso ao 4; o 4 parece pesado ao 7." },
  "4-8":{ level:"neutral",  title:"Vulnerabilidade vs Força",    desc:"Ambos intensos e autênticos. Podem criar vínculo profundo se o 8 suavizar e o 4 se firmar." },
  "4-9":{ level:"synergy",  title:"Beleza + Paz",                desc:"Ambos valorizam profundidade e experiências significativas. Criam espaços de criatividade e reflexão." },
  "5-6":{ level:"synergy",  title:"Análise + Precaução",         desc:"Ambos pensam antes de agir e antecipam riscos. Dupla excelente para planejamento e gestão de riscos." },
  "5-7":{ level:"tension",  title:"Contenção vs Expansão",       desc:"O 5 preserva recursos; o 7 os expande. O 7 esgota o 5; o 5 frustra o 7 com restrições." },
  "5-8":{ level:"neutral",  title:"Mente vs Força",              desc:"O 5 lidera pelo conhecimento; o 8 pela assertividade. Respeito mútuo ou colisão de abordagens." },
  "5-9":{ level:"synergy",  title:"Quietude + Reflexão",         desc:"Ambos preferem ambientes calmos e trabalho autônomo. Respeitam o espaço um do outro naturalmente." },
  "6-7":{ level:"neutral",  title:"Segurança vs Aventura",       desc:"O 6 quer previsibilidade; o 7 quer novidade. Equilibram riscos juntos se houver confiança." },
  "6-8":{ level:"tension",  title:"Autoridade vs Questionamento",desc:"O 8 age com autoridade; o 6 questiona motivações e teme ser controlado. Requer muita transparência." },
  "6-9":{ level:"synergy",  title:"Lealdade + Harmonia",         desc:"Dupla extremamente estável e confiável. Ambos priorizam o coletivo e evitam conflitos desnecessários." },
  "7-8":{ level:"neutral",  title:"Energia + Poder",             desc:"Ambos expansivos e de forte presença. Força dinâmica ou colisão pela dominância do espaço." },
  "7-9":{ level:"synergy",  title:"Leveza + Calma",              desc:"Ambos evitam tensão e buscam experiências positivas. Podem procrastinar conflitos necessários." },
  "8-9":{ level:"neutral",  title:"Força vs Passividade",        desc:"O 8 é direto e confrontador; o 9 evita conflito. O 9 pode ceder demais; o 8 pode dominar sem perceber." },
};

export const getCompat = (a, b) => {
  const key = a < b ? `${a}-${b}` : `${b}-${a}`;
  return COMPAT_RAW[key] || { level:"neutral", title:"Par não mapeado", desc:"" };
};

export const QUESTIONS_PER_TYPE = 6;
export const SCALE_LABELS = ["Não me identifico","Pouco","Às vezes","Bastante","Me identifico muito"];

export const QUESTION_BANK = [
  {id:101,type:1,text:"Tenho um senso interno muito claro do que é certo e errado."},
  {id:102,type:1,text:"Fico incomodado quando as coisas não são feitas da maneira correta."},
  {id:103,type:1,text:"Uma voz interior crítica frequentemente aponta meus erros e imperfeições."},
  {id:104,type:1,text:"Sinto responsabilidade de melhorar o ambiente ao meu redor."},
  {id:105,type:1,text:"Sou muito exigente comigo mesmo quando cometo erros."},
  {id:106,type:1,text:"Tenho dificuldade de relaxar quando algo importante não foi feito da forma certa."},
  {id:107,type:1,text:"Costumo notar detalhes que outros ignoram, especialmente quando algo está errado."},
  {id:108,type:1,text:"Sinto desconforto real quando vejo injustiça ou desonestidade acontecendo."},
  {id:109,type:1,text:"Me esforço para ser um exemplo de integridade no trabalho e na vida pessoal."},
  {id:110,type:1,text:"Tenho dificuldade de entregar algo que considero incompleto ou abaixo do padrão."},
  {id:111,type:1,text:"Criar processos e organizar sistemas me dá satisfação genuína."},
  {id:112,type:1,text:"Me irrito quando regras claramente corretas são ignoradas por conveniência."},
  {id:113,type:1,text:"Frequentemente reviso meu próprio trabalho várias vezes antes de considerá-lo pronto."},
  {id:114,type:1,text:"Sinto que tenho uma missão de fazer o certo, mesmo que seja mais difícil."},
  {id:115,type:1,text:"Críticas ao meu trabalho me afetam profundamente, mesmo quando são construtivas."},
  {id:116,type:1,text:"Tenho padrões elevados que aplico a mim e inconscientemente aos outros também."},
  {id:117,type:1,text:"Sinto raiva quando vejo pessoas irresponsáveis em posições de poder."},
  {id:118,type:1,text:"Prefiro fazer uma tarefa corretamente a fazê-la rapidamente."},
  {id:119,type:1,text:"Acredito que sempre há uma maneira melhor de fazer qualquer coisa."},
  {id:120,type:1,text:"Me sinto culpado quando não cumpro meus próprios padrões de conduta."},
  {id:121,type:1,text:"Valorizo disciplina e autocontrole como virtudes fundamentais."},
  {id:122,type:1,text:"Tenho dificuldade de delegar porque temo que o resultado não atinja meu padrão."},
  {id:123,type:1,text:"Noto automaticamente o que está fora do lugar ou fora do padrão esperado."},
  {id:124,type:1,text:"Quando alguém age de forma antiética, fico genuinamente perturbado."},
  {id:125,type:1,text:"Costumo refazer o que outros fizeram para deixar do jeito que considero correto."},
  {id:126,type:1,text:"Sinto orgulho quando entrego algo de alta qualidade, mesmo que leve mais tempo."},
  {id:127,type:1,text:"Tenho um senso claro de dever que me motiva mais do que reconhecimento externo."},
  {id:128,type:1,text:"Fico frustrado comigo mesmo quando não consigo manter meus ideais de comportamento."},
  {id:129,type:1,text:"Me preocupo se estou sendo justo em todas as minhas decisões."},
  {id:130,type:1,text:"Prefiro recusar uma oportunidade do que agir de forma que considero errada."},
  {id:131,type:1,text:"Tenho dificuldade de aceitar que 'bom o suficiente' é aceitável."},
  {id:132,type:1,text:"Sinto prazer genuíno em melhorar sistemas, processos ou situações imperfeitas."},
  {id:133,type:1,text:"Acredito que melhoria contínua é uma responsabilidade moral, não apenas profissional."},
  {id:201,type:2,text:"Antecipo as necessidades das pessoas antes mesmo que elas as expressem."},
  {id:202,type:2,text:"Prefiro ser quem ajuda a ser quem pede ajuda."},
  {id:203,type:2,text:"Sinto que meu valor vem de ser útil e indispensável para os outros."},
  {id:204,type:2,text:"Fazer o outro se sentir bem me traz satisfação genuína."},
  {id:205,type:2,text:"Às vezes negligencio minhas próprias necessidades para atender as dos outros."},
  {id:206,type:2,text:"Me sinto desconfortável quando não tenho alguém para apoiar ou cuidar."},
  {id:207,type:2,text:"Tenho facilidade em perceber quando alguém está mal emocionalmente, mesmo sem falar."},
  {id:208,type:2,text:"Me sinto rejeitado quando minha ajuda não é aceita ou reconhecida."},
  {id:209,type:2,text:"Frequentemente coloco os sentimentos dos outros acima dos meus em decisões cotidianas."},
  {id:210,type:2,text:"Gosto de ser o tipo de pessoa com quem todos sabem que podem contar."},
  {id:211,type:2,text:"Sinto orgulho quando consigo fazer alguém se sentir visto, cuidado e valorizado."},
  {id:212,type:2,text:"Adapto minha personalidade ao que percebo que o outro precisa de mim."},
  {id:213,type:2,text:"Quando alguém está em crise, meu instinto imediato é agir para ajudar."},
  {id:214,type:2,text:"Tenho dificuldade em dizer não quando alguém precisa de mim, mesmo estando sobrecarregado."},
  {id:215,type:2,text:"Me sinto mais significativo quando estou contribuindo para o bem-estar de alguém."},
  {id:216,type:2,text:"Às vezes fico ressentido quando não recebo reconhecimento pela ajuda que ofereço."},
  {id:217,type:2,text:"Tenho facilidade em criar conexões emocionais com pessoas que acabei de conhecer."},
  {id:218,type:2,text:"Me preocupo se as pessoas ao meu redor estão bem, mesmo quando não é minha responsabilidade."},
  {id:219,type:2,text:"Tenho dificuldade de identificar o que eu mesmo quero quando foco nas necessidades alheias."},
  {id:220,type:2,text:"Sentir que sou necessário me dá um senso de segurança emocional."},
  {id:221,type:2,text:"Observo sutilezas no comportamento dos outros que muitos ignoram."},
  {id:222,type:2,text:"Frequentemente faço coisas pelos outros sem ser pedido, porque percebo que precisam."},
  {id:223,type:2,text:"Me sinto culpado quando foco em mim mesmo em vez de ajudar quem está ao meu redor."},
  {id:224,type:2,text:"Sinto que meus relacionamentos são o centro mais importante da minha vida."},
  {id:225,type:2,text:"Tenho dificuldade de receber cuidado sem sentir que estou sendo um fardo."},
  {id:226,type:2,text:"Gosto de surpreender as pessoas com gestos de cuidado que mostram que presto atenção nelas."},
  {id:227,type:2,text:"Me preocupo se as pessoas gostam de mim ou se estou decepcionando alguém."},
  {id:228,type:2,text:"Quando alguém que cuido passa por dificuldades, sinto as emoções deles como se fossem minhas."},
  {id:229,type:2,text:"Tenho dificuldade de estabelecer limites claros em relacionamentos."},
  {id:230,type:2,text:"Sinto que dar é mais natural do que receber."},
  {id:231,type:2,text:"Me motivo mais quando sei que meu trabalho impacta diretamente o bem-estar das pessoas."},
  {id:232,type:2,text:"Costumo ser o ponto de apoio emocional do grupo em que estou inserido."},
  {id:233,type:2,text:"Tenho medo de ser percebido como egoísta se priorizar minhas próprias necessidades."},
  {id:301,type:3,text:"Me preocupo com como sou percebido em contextos profissionais."},
  {id:302,type:3,text:"Adapto minha forma de me apresentar dependendo do público que tenho à frente."},
  {id:303,type:3,text:"Sou movido por metas, conquistas e resultados concretos."},
  {id:304,type:3,text:"Eficiência é algo que valorizo profundamente em mim e nos outros."},
  {id:305,type:3,text:"Perder tempo ou ser ineficiente me incomoda profundamente."},
  {id:306,type:3,text:"Tenho facilidade em identificar o que é necessário para ter sucesso em qualquer contexto."},
  {id:307,type:3,text:"Sinto uma satisfação profunda quando alcanço uma meta que me propus."},
  {id:308,type:3,text:"Minha imagem e reputação profissional são muito importantes para mim."},
  {id:309,type:3,text:"Tenho facilidade em motivar outras pessoas e criar entusiasmo em torno de um objetivo."},
  {id:310,type:3,text:"Costumo planejar minha carreira e trajetória com clareza e intencionalidade."},
  {id:311,type:3,text:"Me adapto rapidamente ao ambiente para ser percebido como competente e bem-sucedido."},
  {id:312,type:3,text:"Sinto desconforto quando fracasso ou quando minha performance está abaixo do esperado."},
  {id:313,type:3,text:"Tenho um senso natural de como me posicionar e me destacar em qualquer situação."},
  {id:314,type:3,text:"Funciono muito bem sob pressão — desafios me energizam em vez de me paralisar."},
  {id:315,type:3,text:"Às vezes me pergunto se perdi contato com o que realmente quero versus o que me faz parecer bem."},
  {id:316,type:3,text:"Tenho uma capacidade acima da média de identificar oportunidades e agir rapidamente."},
  {id:317,type:3,text:"Me sinto realizado quando recebo reconhecimento pelos resultados que entrego."},
  {id:318,type:3,text:"Costumo ter várias iniciativas em paralelo e consigo gerenciar bem essa complexidade."},
  {id:319,type:3,text:"Sinto que falhar publicamente é uma das coisas que mais temo."},
  {id:320,type:3,text:"Tenho dificuldade de relaxar quando sinto que ainda há coisas a conquistar."},
  {id:321,type:3,text:"Me comparo naturalmente com outros para avaliar onde estou na minha trajetória."},
  {id:322,type:3,text:"Tenho facilidade em inspirar confiança e credibilidade nas pessoas ao meu redor."},
  {id:323,type:3,text:"Gosto de ser visto como alguém bem-sucedido e capaz."},
  {id:324,type:3,text:"Às vezes priorizo a aparência de sucesso em vez do processo genuíno de crescimento."},
  {id:325,type:3,text:"Sou altamente produtivo e sei como entregar resultados mesmo com recursos limitados."},
  {id:326,type:3,text:"Tenho facilidade em liderar projetos e direcionar equipes para metas claras."},
  {id:327,type:3,text:"Me preocupo com o legado e o impacto que deixo em cada ambiente que passo."},
  {id:328,type:3,text:"Sinto que o que faço define quem sou — e isso às vezes me pesa."},
  {id:329,type:3,text:"Tenho facilidade de ajustar minha mensagem dependendo do que o ouvinte precisa escutar."},
  {id:330,type:3,text:"Sou muito focado e raramente me deixo distrair quando tenho um objetivo claro."},
  {id:331,type:3,text:"Prefiro contextos em que o mérito e o desempenho são claramente avaliados."},
  {id:332,type:3,text:"Sinto que preciso estar sempre evoluindo para me sentir relevante."},
  {id:333,type:3,text:"Tenho muita clareza sobre minhas metas de curto e longo prazo."},
  {id:401,type:4,text:"Sinto que sou fundamentalmente diferente da maioria das pessoas."},
  {id:402,type:4,text:"Tenho uma relação intensa com a melancolia e a nostalgia."},
  {id:403,type:4,text:"Preciso que minha vida tenha profundidade, beleza e significado."},
  {id:404,type:4,text:"Às vezes sinto que algo importante está faltando na minha vida."},
  {id:405,type:4,text:"Prefiro experiências autênticas e únicas às convencionais."},
  {id:406,type:4,text:"Sinto emoções de forma muito intensa, tanto positivas quanto negativas."},
  {id:407,type:4,text:"Tenho uma sensibilidade estética aguçada — beleza e arte me afetam profundamente."},
  {id:408,type:4,text:"Me identifico mais com histórias e personagens que têm profundidade emocional."},
  {id:409,type:4,text:"Frequentemente me sinto incompreendido pelas pessoas ao meu redor."},
  {id:410,type:4,text:"Tenho uma visão de mundo muito pessoal que dificilmente consigo comunicar por completo."},
  {id:411,type:4,text:"Minha identidade é muito ligada à forma como me expresso criativamente."},
  {id:412,type:4,text:"Sinto que os outros têm uma leveza natural que parece me faltar."},
  {id:413,type:4,text:"Tenho dificuldade em aceitar o cotidiano sem que pareça vazio ou sem sentido."},
  {id:414,type:4,text:"Me emociono com facilidade em situações que a maioria das pessoas nem nota."},
  {id:415,type:4,text:"Tenho um forte desejo de ser visto como único e não apenas mais um na multidão."},
  {id:416,type:4,text:"Às vezes me comparo com os outros e sinto que estou sempre faltando algo fundamental."},
  {id:417,type:4,text:"Tenho uma relação complexa com o passado — ele me atrai e me prende ao mesmo tempo."},
  {id:418,type:4,text:"Prefiro um trabalho que tenha significado pessoal do que um que pague bem sem propósito."},
  {id:419,type:4,text:"Sinto que minha dor e minha melancolia fazem parte do que me torna único."},
  {id:420,type:4,text:"Tenho dificuldade em manter relacionamentos que me parecem superficiais ou vazios."},
  {id:421,type:4,text:"Me inspiro profundamente em arte, música e expressão criativa."},
  {id:422,type:4,text:"Tenho um senso aguçado de quem sou e do que não abro mão na minha identidade."},
  {id:423,type:4,text:"Frequentemente fantasio sobre uma versão mais perfeita da minha vida."},
  {id:424,type:4,text:"Sinto que expressar o que sinto de forma autêntica é uma necessidade, não uma opção."},
  {id:425,type:4,text:"Tenho momentos de intensa inspiração seguidos por períodos de esvaziamento emocional."},
  {id:426,type:4,text:"Me sinto mais vivo em experiências de alta intensidade emocional."},
  {id:427,type:4,text:"Às vezes me perco em devaneios sobre como as coisas poderiam ter sido diferentes."},
  {id:428,type:4,text:"Tenho facilidade em criar trabalhos originais que refletem minha perspectiva única."},
  {id:429,type:4,text:"Me sinto atraído por temas de perda, saudade e transformação."},
  {id:430,type:4,text:"Tenho uma forte necessidade de que meu trabalho reflita quem eu sou de verdade."},
  {id:431,type:4,text:"Às vezes idealizo o que não tenho e desvalorizo o que está presente na minha vida."},
  {id:432,type:4,text:"Me relaciono melhor com pessoas que toleram profundidade e intensidade emocional."},
  {id:433,type:4,text:"Tenho dificuldade de seguir rotinas que me parecem mecânicas ou sem alma."},
  {id:501,type:5,text:"Preciso de muito tempo sozinho para recarregar minhas energias."},
  {id:502,type:5,text:"Prefiro observar e analisar uma situação antes de participar dela."},
  {id:503,type:5,text:"Tenho curiosidade intensa e adoro me aprofundar em temas específicos."},
  {id:504,type:5,text:"Protejo meu espaço, tempo e energia com muito cuidado."},
  {id:505,type:5,text:"Prefiro pensar com calma antes de tomar qualquer decisão."},
  {id:506,type:5,text:"Quando estou sobrecarregado emocionalmente, meu instinto é me isolar."},
  {id:507,type:5,text:"Me sinto mais confortável com ideias e conceitos do que com emoções e conflitos."},
  {id:508,type:5,text:"Prefiro comunicar minhas ideias por escrito ou de forma estruturada."},
  {id:509,type:5,text:"Sinto que interações sociais intensas me consomem energia de forma desproporcional."},
  {id:510,type:5,text:"Tenho uma capacidade acima da média de me concentrar em um problema por longos períodos."},
  {id:511,type:5,text:"Prefiro dominar um assunto completamente antes de falar sobre ele."},
  {id:512,type:5,text:"Tenho dificuldade em compartilhar recursos — tempo, atenção, energia — sem sentir escassez."},
  {id:513,type:5,text:"Me sinto mais à vontade em ambientes previsíveis e sem muitas demandas sociais."},
  {id:514,type:5,text:"Gosto de entender como as coisas funcionam em seu nível mais profundo."},
  {id:515,type:5,text:"Tenho facilidade em manter objetividade em situações em que outros ficam emocionais."},
  {id:516,type:5,text:"Às vezes as pessoas percebem que sou distante, mas eu simplesmente preciso de espaço."},
  {id:517,type:5,text:"Prefiro ter poucos relacionamentos profundos do que muitos superficiais."},
  {id:518,type:5,text:"Sinto prazer genuíno em acumular conhecimento, mesmo que nunca use tudo que aprendo."},
  {id:519,type:5,text:"Tenho dificuldade com interrupções enquanto estou no meio de um pensamento complexo."},
  {id:520,type:5,text:"Me sinto mais competente quando tenho todas as informações necessárias antes de agir."},
  {id:521,type:5,text:"Costumo observar os grupos antes de me integrar a eles."},
  {id:522,type:5,text:"Tenho uma tendência a minimizar minhas necessidades para depender menos dos outros."},
  {id:523,type:5,text:"Me sinto desconfortável quando preciso compartilhar muito de mim mesmo com estranhos."},
  {id:524,type:5,text:"Tenho um apreço especial por pessoas que são competentes e diretas."},
  {id:525,type:5,text:"Às vezes demoro para agir porque quero ter certeza de que entendi tudo completamente."},
  {id:526,type:5,text:"Me interesso mais pelos bastidores e mecanismos das coisas do que pela superfície."},
  {id:527,type:5,text:"Tenho dificuldade de expressar emoções no calor do momento — processo mais tarde, sozinho."},
  {id:528,type:5,text:"Sinto que meu valor está no que sei e na qualidade do meu pensamento."},
  {id:529,type:5,text:"Prefiro um ambiente de trabalho silencioso e com pouca interrupção."},
  {id:530,type:5,text:"Frequentemente percebo conexões e padrões que outros não notam."},
  {id:531,type:5,text:"Tenho uma lista mental de tópicos que quero estudar e explorar com profundidade."},
  {id:532,type:5,text:"Me sinto desrespeitado quando meu tempo ou concentração são interrompidos sem necessidade."},
  {id:533,type:5,text:"Prefiro resolver problemas sozinho antes de pedir ajuda."},
  {id:601,type:6,text:"Frequentemente antecipo problemas ou cenários negativos antes que aconteçam."},
  {id:602,type:6,text:"Lealdade e confiança são valores centrais na minha vida."},
  {id:603,type:6,text:"Questiono as motivações das pessoas antes de confiar completamente nelas."},
  {id:604,type:6,text:"Sinto ansiedade ao tomar decisões importantes sem apoio de quem confio."},
  {id:605,type:6,text:"Preciso de referências ou aprovação de quem confio para me sentir seguro."},
  {id:606,type:6,text:"Costumo preparar planos alternativos caso algo dê errado."},
  {id:607,type:6,text:"Tenho dificuldade de confiar em pessoas que parecem confiantes demais ou que nunca duvidam."},
  {id:608,type:6,text:"Sou extremamente leal a quem conquistou minha confiança ao longo do tempo."},
  {id:609,type:6,text:"Quando algo parece bom demais para ser verdade, fico desconfiado automaticamente."},
  {id:610,type:6,text:"Tenho uma tendência a pensar nos piores cenários possíveis antes de agir."},
  {id:611,type:6,text:"Me sinto mais seguro em ambientes com regras claras e autoridades confiáveis."},
  {id:612,type:6,text:"Valorizo consistência — prefiro alguém previsível a alguém emocionante mas instável."},
  {id:613,type:6,text:"Fico desconfortável quando não sei o que esperar de uma situação ou pessoa."},
  {id:614,type:6,text:"Tenho uma capacidade natural de identificar riscos e vulnerabilidades em planos."},
  {id:615,type:6,text:"Me sinto mais ansioso quando preciso tomar decisões rápidas sem tempo de avaliar."},
  {id:616,type:6,text:"Costumo questionar autoridades que não justificam suas decisões de forma clara."},
  {id:617,type:6,text:"Tenho dificuldade de me comprometer completamente sem ter garantias mínimas."},
  {id:618,type:6,text:"Me sinto responsável por proteger as pessoas ao meu redor de possíveis ameaças."},
  {id:619,type:6,text:"Quando algo muda de repente, meu primeiro instinto é buscar o que pode dar errado."},
  {id:620,type:6,text:"Busco apoio de amigos ou colegas de confiança antes de tomar decisões importantes."},
  {id:621,type:6,text:"Tenho dificuldade de relaxar quando sinto que a situação ao meu redor está instável."},
  {id:622,type:6,text:"Fico vigilante quando percebo sinais de que alguém não está sendo completamente honesto."},
  {id:623,type:6,text:"Me identifico muito com grupos ou causas em que acredito profundamente."},
  {id:624,type:6,text:"Tenho um senso aguçado de quando algo está fora do lugar em uma situação ou relacionamento."},
  {id:625,type:6,text:"Prefiro ambientes de trabalho onde os papéis e responsabilidades estão bem definidos."},
  {id:626,type:6,text:"Confio mais em quem demonstra comprometimento de longo prazo do que em promessas imediatas."},
  {id:627,type:6,text:"Me sinto desconfortável com mudanças frequentes de direção sem explicação clara."},
  {id:628,type:6,text:"Tenho um compromisso profundo com as pessoas e causas às quais me dedico."},
  {id:629,type:6,text:"Às vezes duvido das minhas próprias percepções e busco validação externa."},
  {id:630,type:6,text:"Quando me sinto ameaçado, posso me tornar tanto extremamente cauteloso quanto surpreendentemente confrontador."},
  {id:631,type:6,text:"Valorizo muito a previsibilidade e a estabilidade nos meus relacionamentos profissionais."},
  {id:632,type:6,text:"Me sinto mais seguro quando tenho uma rede de suporte sólida ao meu redor."},
  {id:633,type:6,text:"Tenho facilidade em antecipar as objeções dos outros antes mesmo de apresentar uma ideia."},
  {id:701,type:7,text:"Me entedio facilmente com rotinas e busco constantemente novas experiências."},
  {id:702,type:7,text:"Fico animado com possibilidades e planos futuros."},
  {id:703,type:7,text:"Tenho dificuldade de ficar com sentimentos negativos por muito tempo."},
  {id:704,type:7,text:"Prefiro manter opções abertas a me comprometer com uma única direção."},
  {id:705,type:7,text:"Tenho facilidade em encontrar o lado positivo de qualquer situação."},
  {id:706,type:7,text:"Frequentemente começo novos projetos antes de terminar os anteriores."},
  {id:707,type:7,text:"Me sinto vivo quando estou explorando algo novo, aprendendo ou aventurando."},
  {id:708,type:7,text:"Tenho uma capacidade natural de tornar qualquer ambiente mais leve e divertido."},
  {id:709,type:7,text:"Fico inquieto quando preso em rotinas sem variação por muito tempo."},
  {id:710,type:7,text:"Prefiro pensar no futuro e nas possibilidades do que me deter no passado ou nos problemas."},
  {id:711,type:7,text:"Tenho facilidade em conectar ideias de diferentes áreas de forma criativa."},
  {id:712,type:7,text:"Me sinto desconfortável quando fico parado ou quando não há nada novo acontecendo."},
  {id:713,type:7,text:"Frequentemente planejo várias experiências e atividades para o futuro ao mesmo tempo."},
  {id:714,type:7,text:"Tenho dificuldade de aprofundar em temas que exigem muito tempo sem recompensa visível."},
  {id:715,type:7,text:"Prefiro um ambiente de trabalho dinâmico, com variedade e novidade constante."},
  {id:716,type:7,text:"Tenho facilidade em improvisar e encontrar soluções criativas em situações inesperadas."},
  {id:717,type:7,text:"Me sinto atraído por ideias inovadoras e pouco convencionais."},
  {id:718,type:7,text:"Às vezes evito situações de dor ou desconforto me jogando em novas atividades."},
  {id:719,type:7,text:"Tenho dificuldade de tolerar ambientes excessivamente sérios ou rígidos."},
  {id:720,type:7,text:"Me sinto mais motivado quando tenho liberdade para explorar e experimentar."},
  {id:721,type:7,text:"Frequentemente tenho mais ideias do que tempo ou energia para executar."},
  {id:722,type:7,text:"Me relaciono facilmente com pessoas de perfis muito diferentes."},
  {id:723,type:7,text:"Tenho uma energia contagiante que naturalmente anima os ambientes em que estou."},
  {id:724,type:7,text:"Às vezes me comprometo com menos do que poderia para preservar minha liberdade."},
  {id:725,type:7,text:"Tenho facilidade em ver oportunidades onde outros veem obstáculos."},
  {id:726,type:7,text:"Me sinto limitado em contextos que exigem foco exclusivo em uma única tarefa por muito tempo."},
  {id:727,type:7,text:"Adoro experiências novas — viagens, comidas, conhecimentos, pessoas."},
  {id:728,type:7,text:"Tenho dificuldade de sentar com a dor emocional — prefiro transformá-la em ação ou humor."},
  {id:729,type:7,text:"Me sinto mais produtivo quando tenho autonomia para decidir como e quando trabalhar."},
  {id:730,type:7,text:"Às vezes tomo decisões impulsivas porque a ideia parece empolgante no momento."},
  {id:731,type:7,text:"Prefiro conversas que abram possibilidades a conversas que fechem ou limitem opções."},
  {id:732,type:7,text:"Tenho facilidade em manter o bom humor mesmo em situações difíceis."},
  {id:733,type:7,text:"Me sinto atraído por projetos com grande escopo e impacto potencial."},
  {id:801,type:8,text:"Não tenho medo de conflito — às vezes até me sinto mais vivo nele."},
  {id:802,type:8,text:"Protejo com intensidade as pessoas que amo ou que são vulneráveis."},
  {id:803,type:8,text:"Preciso ter controle sobre minha vida e não aceito me sentir controlado."},
  {id:804,type:8,text:"Sou direto e prefiro a verdade dura a uma mentira gentil."},
  {id:805,type:8,text:"Tenho dificuldade em mostrar vulnerabilidade ou fraqueza para os outros."},
  {id:806,type:8,text:"Me irrito quando percebo injustiça ou manipulação acontecendo ao meu redor."},
  {id:807,type:8,text:"Tomo decisões com rapidez e confiança, mesmo com informações incompletas."},
  {id:808,type:8,text:"Prefiro liderar do que seguir — especialmente quando sinto que a liderança é fraca."},
  {id:809,type:8,text:"Tenho uma presença forte que as pessoas sentem mesmo sem eu dizer nada."},
  {id:810,type:8,text:"Me sinto atraído por desafios que a maioria das pessoas evitaria."},
  {id:811,type:8,text:"Quando me comprometo com alguém, é com intensidade total — e espero reciprocidade."},
  {id:812,type:8,text:"Fico com raiva quando percebo que alguém está tentando me manipular ou enganar."},
  {id:813,type:8,text:"Prefiro um confronto honesto a uma paz falsa."},
  {id:814,type:8,text:"Tenho dificuldade de obedecer regras que me parecem arbitrárias ou injustas."},
  {id:815,type:8,text:"Me sinto responsável por proteger aqueles que não conseguem se proteger."},
  {id:816,type:8,text:"Tenho uma energia física e emocional muito intensa que pode intimidar as pessoas."},
  {id:817,type:8,text:"Prefiro ser respeitado do que amado — embora valorize ambos."},
  {id:818,type:8,text:"Tenho pouca paciência para rodeios — prefiro que as pessoas sejam diretas comigo."},
  {id:819,type:8,text:"Me sinto mais confortável quando tenho autonomia total para tomar minhas decisões."},
  {id:820,type:8,text:"Quando algo é injusto, sinto uma necessidade quase física de intervir."},
  {id:821,type:8,text:"Tenho facilidade em identificar quem tem poder real em qualquer situação."},
  {id:822,type:8,text:"Às vezes exagero na intensidade de minhas reações e só percebo isso depois."},
  {id:823,type:8,text:"Me sinto desrespeitado quando alguém tenta me impor limites sem justificativa."},
  {id:824,type:8,text:"Tenho um forte instinto de justiça que orienta muitas das minhas ações."},
  {id:825,type:8,text:"Prefiro enfrentar os problemas de frente em vez de contorná-los diplomaticamente."},
  {id:826,type:8,text:"Tenho dificuldade de deixar transparecer minha sensibilidade — parece fraqueza."},
  {id:827,type:8,text:"Me sinto mais vivo em situações de alta intensidade e alto risco."},
  {id:828,type:8,text:"Tenho um lado extremamente protetor que emerge quando alguém que amo está ameaçado."},
  {id:829,type:8,text:"Prefiro ambientes em que a hierarquia é clara e baseada em competência real."},
  {id:830,type:8,text:"Às vezes sou percebido como intimidador, embora não seja minha intenção."},
  {id:831,type:8,text:"Tenho dificuldade de pedir ajuda — prefiro resolver as coisas por conta própria."},
  {id:832,type:8,text:"Me importo profundamente com as pessoas, mas expresso isso através de ações, não palavras."},
  {id:833,type:8,text:"Prefiro criar minhas próprias regras do que seguir as dos outros."},
  {id:901,type:9,text:"Evito conflitos e prefiro encontrar formas de mediar desentendimentos."},
  {id:902,type:9,text:"Às vezes perco de vista o que eu quero, ocupado com o que os outros querem."},
  {id:903,type:9,text:"Me sinto confortável em rotinas tranquilas e previsíveis."},
  {id:904,type:9,text:"Tenho dificuldade de dizer não para pessoas que gosto."},
  {id:905,type:9,text:"Consigo ver o mérito de perspectivas completamente opostas com facilidade."},
  {id:906,type:9,text:"Às vezes procrastino decisões importantes para evitar tensão ou conflito."},
  {id:907,type:9,text:"Tenho uma capacidade natural de criar harmonia em grupos em conflito."},
  {id:908,type:9,text:"Me sinto desconfortável quando percebo que alguém está bravo ou insatisfeito comigo."},
  {id:909,type:9,text:"Prefiro um ambiente tranquilo e estável a um ambiente agitado e imprevisível."},
  {id:910,type:9,text:"Tenho facilidade em aceitar e adaptar às preferências dos outros."},
  {id:911,type:9,text:"Às vezes não tenho clareza sobre o que eu mesmo quero ou prefiro."},
  {id:912,type:9,text:"Me sinto bem quando todos ao meu redor estão bem — e isso me importa genuinamente."},
  {id:913,type:9,text:"Tenho dificuldade de afirmar minha opinião quando sei que vai gerar desconforto."},
  {id:914,type:9,text:"Prefiro ceder em pequenos pontos a criar uma tensão desnecessária."},
  {id:915,type:9,text:"Me sinto esgotado em ambientes com muitos conflitos ou pressões simultâneas."},
  {id:916,type:9,text:"Tenho uma paciência natural que as pessoas ao meu redor percebem e valorizam."},
  {id:917,type:9,text:"Às vezes deixo as coisas acumularem em vez de resolver conflitos pequenos no momento."},
  {id:918,type:9,text:"Me sinto mais à vontade quando sei que a situação é previsível e estável."},
  {id:919,type:9,text:"Tenho dificuldade de priorizar minhas próprias necessidades quando outros estão precisando."},
  {id:920,type:9,text:"Costumo adaptar meu ritmo ao do grupo em vez de impor o meu."},
  {id:921,type:9,text:"Me incomoda profundamente quando há discórdia persistente em um grupo ao qual pertenço."},
  {id:922,type:9,text:"Tenho facilidade em ouvir os dois lados de uma história sem julgamento prematuro."},
  {id:923,type:9,text:"Às vezes me perco em atividades secundárias para evitar o que precisa ser feito mas gera tensão."},
  {id:924,type:9,text:"Me relaciono bem com praticamente qualquer tipo de pessoa — tenho uma energia acolhedora."},
  {id:925,type:9,text:"Tenho dificuldade de reconhecer e expressar minha própria raiva."},
  {id:926,type:9,text:"Prefiro ambientes colaborativos onde as decisões são tomadas em consenso."},
  {id:927,type:9,text:"Às vezes concordo com algo apenas para evitar a discussão, sem realmente concordar."},
  {id:928,type:9,text:"Me sinto desconfortável quando preciso confrontar alguém diretamente."},
  {id:929,type:9,text:"Tenho um ritmo próprio que funciona bem para mim, mas que outros podem perceber como lento."},
  {id:930,type:9,text:"Costumo priorizar o bem-estar coletivo acima do meu próprio."},
  {id:931,type:9,text:"Às vezes me esqueco de mim mesmo em meio às demandas e expectativas dos outros."},
  {id:932,type:9,text:"Tenho uma presença reconfortante — as pessoas se sentem seguras ao meu redor."},
  {id:933,type:9,text:"Me identifico com o papel de mediador e pacificador em qualquer grupo que faço parte."},
];

export function drawQuestions() {
  const result = [];
  for (let t = 1; t <= 9; t++) {
    const pool = QUESTION_BANK.filter(q => q.type === t);
    const shuffled = [...pool].sort(() => Math.random() - 0.5);
    result.push(...shuffled.slice(0, QUESTIONS_PER_TYPE));
  }
  return result.sort(() => Math.random() - 0.5);
}
